server:
  port: 8092

spring:
  kafka:
    bootstrap-servers: 192.168.94.201:9092,192.168.94.201:9093,192.168.94.201:9094
    producer:
      retries: 0
      batch-size: 1384
      buffer-memory: 33554432
      acks: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: privateGroup1
      #latest
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
